package btl2.entiny;
// Generated Jun 29, 2020 9:30:22 PM by Hibernate Tools 4.3.1



/**
 * Hinhanh generated by hbm2java
 */
public class Hinhanh  implements java.io.Serializable {


     private int id;
     private Hoinghi hoinghi;
     private String hinhanh;

    public Hinhanh() {
    }

	
    public Hinhanh(int id) {
        this.id = id;
    }
    public Hinhanh(int id, Hoinghi hoinghi, String hinhanh) {
       this.id = id;
       this.hoinghi = hoinghi;
       this.hinhanh = hinhanh;
    }
   
    public Hinhanh(Hoinghi hoinghi, String hinhanh) {
       this.hoinghi = hoinghi;
       this.hinhanh = hinhanh;
    }
    
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Hoinghi getHoinghi() {
        return this.hoinghi;
    }
    
    public void setHoinghi(Hoinghi hoinghi) {
        this.hoinghi = hoinghi;
    }
    public String getHinhanh() {
        return this.hinhanh;
    }
    
    public void setHinhanh(String hinhanh) {
        this.hinhanh = hinhanh;
    }




}


