package btl2.entiny;
// Generated Jun 29, 2020 9:30:22 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

/**
 * Hoinghi generated by hbm2java
 */
@Entity
public class Hoinghi  implements java.io.Serializable {

     @Id
     @GeneratedValue
     private int id;
     private Diadiem diadiem;
     private String ten;
     private String mota;
     private String motachitiet;
     private Date thoigianbd;
     private Date thoigiankt;
     private Integer soluongnguoithamgia;
     private int soLuongDaThamGia;
     private boolean hetHan = false;
     private Set nguoithamgiahoinghis = new HashSet(0);
     private Set hinhanhs = new HashSet(0);

    public Hoinghi() {
    }

    public Hoinghi(Hoinghi hoinghi) {
       this.id = hoinghi.id;
       this.diadiem = hoinghi.diadiem;
       this.ten = hoinghi.ten;
       this.mota = hoinghi.mota;
       this.motachitiet = hoinghi.motachitiet;
       this.thoigianbd = hoinghi.thoigianbd;
       this.thoigiankt = hoinghi.thoigiankt;
       this.soluongnguoithamgia = hoinghi.soluongnguoithamgia;
       this.nguoithamgiahoinghis = hoinghi.nguoithamgiahoinghis;
       this.soLuongDaThamGia = hoinghi.soLuongDaThamGia;
       this.hinhanhs = hoinghi.hinhanhs;
       if (thoigiankt.before(new Date())){
           this.hetHan = true;
       }
    }
    public Hoinghi(int id) {
        this.id = id;
    }
    public Hoinghi(int id, Diadiem diadiem, String ten, String mota, String motachitiet, Date thoigianbd, Date thoigiankt, Integer soluongnguoithamgia, Set nguoithamgiahoinghis, Set hinhanhs) {
       this.id = id;
       this.diadiem = diadiem;
       this.ten = ten;
       this.mota = mota;
       this.motachitiet = motachitiet;
       this.thoigianbd = thoigianbd;
       this.thoigiankt = thoigiankt;
       this.soluongnguoithamgia = soluongnguoithamgia;
       this.nguoithamgiahoinghis = nguoithamgiahoinghis;
       this.hinhanhs = hinhanhs;
       this.soLuongDaThamGia = nguoithamgiahoinghis.size();
       if (thoigiankt.before(new Date())){
           this.hetHan = true;
       }
    }
    
    public Hoinghi(Diadiem diadiem, String ten, String mota, String motachitiet, Date thoigianbd, Date thoigiankt, Integer soluongnguoithamgia) {
       this.diadiem = diadiem;
       this.ten = ten;
       this.mota = mota;
       this.motachitiet = motachitiet;
       this.thoigianbd = thoigianbd;
       this.thoigiankt = thoigiankt;
       this.soluongnguoithamgia = soluongnguoithamgia;
       if (thoigiankt.before(new Date())){
           this.hetHan = true;
       }
    }
    
    public void setHoinghi(Diadiem diadiem, String ten, String mota, String motachitiet, Date thoigianbd, Date thoigiankt, Integer soluongnguoithamgia) {
       this.diadiem = diadiem;
       this.ten = ten;
       this.mota = mota;
       this.motachitiet = motachitiet;
       this.thoigianbd = thoigianbd;
       this.thoigiankt = thoigiankt;
       this.soluongnguoithamgia = soluongnguoithamgia;
       if (thoigiankt.before(new Date())){
           this.hetHan = true;
       }
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Diadiem getDiadiem() {
        return this.diadiem;
    }
    
    public void setDiadiem(Diadiem diadiem) {
        this.diadiem = diadiem;
    }
    public String getTen() {
        return this.ten;
    }
    
    public void setTen(String ten) {
        this.ten = ten;
    }
    public String getMota() {
        return this.mota;
    }
    
    public void setMota(String mota) {
        this.mota = mota;
    }
    public String getMotachitiet() {
        return this.motachitiet;
    }
    
    public void setMotachitiet(String motachitiet) {
        this.motachitiet = motachitiet;
    }
    public Date getThoigianbd() {
        return this.thoigianbd;
    }
    
    public void setThoigianbd(Date thoigianbd) {
        this.thoigianbd = thoigianbd;
    }
    public Date getThoigiankt() {
        return this.thoigiankt;
    }
    
    public void setThoigiankt(Date thoigiankt) {
        this.thoigiankt = thoigiankt;
        if (thoigiankt.before(new Date())){
           this.hetHan = true;
       }
    }
    public Integer getSoluongnguoithamgia() {
        return this.soluongnguoithamgia;
    }
    
    public void setSoluongnguoithamgia(Integer soluongnguoithamgia) {
        this.soluongnguoithamgia = soluongnguoithamgia;
    }
    public Set getNguoithamgiahoinghis() {
        return this.nguoithamgiahoinghis;
    }
    
    public int getSoLuongDaThamGia() {
        return this.soLuongDaThamGia;
    }
    
    public void setNguoithamgiahoinghis(Set nguoithamgiahoinghis) {
        this.soLuongDaThamGia = nguoithamgiahoinghis.size();
        this.nguoithamgiahoinghis = nguoithamgiahoinghis;
    }
    public Set getHinhanhs() {
        return this.hinhanhs;
    }
    
    public void setHinhanhs(Set hinhanhs) {
        this.hinhanhs = hinhanhs;
    }

    public boolean isHetHan() {
        return hetHan;
    }

    public void setHetHan(boolean hetHan) {
        this.hetHan = hetHan;
    }

    @Override
    public String toString() {
        return getTen()+getMota(); //To change body of generated methods, choose Tools | Templates.
    }

}


