package btl2.entiny;
// Generated Jun 29, 2020 9:30:22 PM by Hibernate Tools 4.3.1



/**
 * NguoithamgiahoinghiId generated by hbm2java
 */
public class NguoithamgiahoinghiId  implements java.io.Serializable {


     private int user;
     private int hoinghi;

    public NguoithamgiahoinghiId() {
    }

    public NguoithamgiahoinghiId(int user, int hoinghi) {
       this.user = user;
       this.hoinghi = hoinghi;
    }
   
    public int getUser() {
        return this.user;
    }
    
    public void setUser(int user) {
        this.user = user;
    }
    public int getHoinghi() {
        return this.hoinghi;
    }
    
    public void setHoinghi(int hoinghi) {
        this.hoinghi = hoinghi;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof NguoithamgiahoinghiId) ) return false;
		 NguoithamgiahoinghiId castOther = ( NguoithamgiahoinghiId ) other; 
         
		 return (this.getUser()==castOther.getUser())
 && (this.getHoinghi()==castOther.getHoinghi());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUser();
         result = 37 * result + this.getHoinghi();
         return result;
   }   


}


