package btl2.entiny;
// Generated Jun 29, 2020 9:30:22 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Nguoithamgiahoinghi generated by hbm2java
 */
public class Nguoithamgiahoinghi  implements java.io.Serializable {


     private NguoithamgiahoinghiId id;
     private Hoinghi hoinghi;
     private User user;
     private Date thoigianthamgia;
     private int isallow;

    public Nguoithamgiahoinghi() {
    }

	
    public Nguoithamgiahoinghi(NguoithamgiahoinghiId id, Hoinghi hoinghi, User user) {
        this.id = id;
        this.hoinghi = hoinghi;
        this.user = user;
    }
    
    public Nguoithamgiahoinghi(NguoithamgiahoinghiId id, Hoinghi hoinghi, User user,int isallow) {
        this.id = id;
        this.hoinghi = hoinghi;
        this.user = user;
        this.isallow = isallow;
    }
    
    public Nguoithamgiahoinghi( Hoinghi hoinghi, User user) {
        this.id = new NguoithamgiahoinghiId(user.getId(),hoinghi.getId());
        this.hoinghi = hoinghi;
        this.user = user;
        this.thoigianthamgia = new Date();
    }
    
    public Nguoithamgiahoinghi(NguoithamgiahoinghiId id, Hoinghi hoinghi, User user, Date thoigianthamgia,int isallow) {
       this.id = id;
       this.hoinghi = hoinghi;
       this.user = user;
       this.thoigianthamgia = thoigianthamgia;
       this.isallow = isallow;
    }
   
    public NguoithamgiahoinghiId getId() {
        return this.id;
    }
    
    public void setId(NguoithamgiahoinghiId id) {
        this.id = id;
    }
    public Hoinghi getHoinghi() {
        return this.hoinghi;
    }
    
    public void setHoinghi(Hoinghi hoinghi) {
        this.hoinghi = hoinghi;
    }
    
    public int getIsallow() {
        return this.isallow;
    }
    
    public void setIsallow(int isallow) {
        this.isallow = isallow;
    }
    
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Date getThoigianthamgia() {
        return this.thoigianthamgia;
    }
    
    public void setThoigianthamgia(Date thoigianthamgia) {
        this.thoigianthamgia = thoigianthamgia;
    }

    @Override
    public String toString() {
        return "Người dùng: "+user.getUsername()+", id: "
                        +user.getId()+" muốn tham gia hội nghị: " 
                        + hoinghi.getTen()+", có id: "+hoinghi.getId(); //To change body of generated methods, choose Tools | Templates.
    }

}


