/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package btl2.GUI;

import btl2.DAO.DiadiemDAO;
import btl2.entiny.Diadiem;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class DialogAddDiadiem extends javax.swing.JFrame {

    /**
     * Creates new form DialogAddDiadiem
     */
    private AddHoiNghi frame = null;
    public DialogAddDiadiem(){
        initComponents();
        setBackground(new Color(0,0,0,0));
        setVisible(true);
        Home.getInstance().setEnabled(false);
    }
    
    public DialogAddDiadiem(AddHoiNghi frame){
        initComponents();
        setBackground(new Color(0,0,0,0));
        setVisible(true);
        Home.getInstance().setEnabled(false);
        this.frame = frame;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        question2 = new javax.swing.JLabel();
        question4 = new javax.swing.JLabel();
        guessJoin = new javax.swing.JFormattedTextField();
        diachi = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        question = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/closeimg.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(370, 40, 16, 16);

        question2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        question2.setForeground(new java.awt.Color(255, 255, 255));
        question2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        question2.setText("Địa chỉ");
        getContentPane().add(question2);
        question2.setBounds(60, 90, 50, 30);

        question4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        question4.setForeground(new java.awt.Color(255, 255, 255));
        question4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        question4.setText("Số người tối đa");
        getContentPane().add(question4);
        question4.setBounds(220, 20, 110, 30);

        guessJoin.setBackground(new java.awt.Color(255, 255, 255));
        guessJoin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        guessJoin.setForeground(new java.awt.Color(51, 51, 51));
        guessJoin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        getContentPane().add(guessJoin);
        guessJoin.setBounds(220, 50, 130, 40);

        diachi.setBackground(new java.awt.Color(255, 255, 255));
        diachi.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        diachi.setForeground(new java.awt.Color(51, 51, 51));
        diachi.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        getContentPane().add(diachi);
        diachi.setBounds(60, 120, 290, 40);

        name.setBackground(new java.awt.Color(255, 255, 255));
        name.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        name.setForeground(new java.awt.Color(51, 51, 51));
        name.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        getContentPane().add(name);
        name.setBounds(60, 50, 140, 40);

        jButton1.setBackground(new java.awt.Color(255, 153, 51));
        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Xác nhận");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(90, 180, 80, 25);

        jButton2.setBackground(new java.awt.Color(255, 153, 51));
        jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Thoát");
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(240, 180, 80, 25);

        question.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        question.setForeground(new java.awt.Color(255, 255, 255));
        question.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        question.setText("Tên");
        getContentPane().add(question);
        question.setBounds(60, 20, 30, 30);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/rsz_rounded-rectangle.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 410, 230);

        setSize(new java.awt.Dimension(412, 230));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        dispose();
        Home.getInstance().setEnabled(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        dispose();   
        Home.getInstance().setEnabled(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        if (name.getText().trim().equals("")||diachi.getText().trim().equals("")||guessJoin.getValue()==null){
            JOptionPane.showMessageDialog(this, "Không bỏ trống trường");
        } else {
            Long l = (Long) guessJoin.getValue();
            if (l.intValue()<=0){
                JOptionPane.showMessageDialog(this, "Số người tham gia là số nguyên dương");
            }
            else {
                JOptionPane.showMessageDialog(this, "Đã thêm");
                DiadiemDAO.addDiadiem(new Diadiem(name.getText().trim(),diachi.getText().trim(),l.intValue()));
                frame.updateListDiaDiem();
                Home.getInstance().setEnabled(true);
                dispose();       
            }
        }
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogAddDiadiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogAddDiadiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogAddDiadiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogAddDiadiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DialogAddDiadiem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField diachi;
    private javax.swing.JFormattedTextField guessJoin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField name;
    private javax.swing.JLabel question;
    private javax.swing.JLabel question2;
    private javax.swing.JLabel question4;
    // End of variables declaration//GEN-END:variables
}
