/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package btl2.GUI;

import btl2.DAO.NguoithamgiahoinghiDAO;
import btl2.entiny.Hoinghi;
import btl2.entiny.Nguoithamgiahoinghi;
import btl2.entiny.NguoithamgiahoinghiId;
import java.awt.Color;
import java.awt.Component;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.ListCellRenderer;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author DELL
 */
public class HNUserItem extends javax.swing.JPanel implements  ListCellRenderer<Hoinghi>{

    /**
     * Creates new form HNUserItem
     */
    public HNUserItem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameHN = new javax.swing.JLabel();
        xetDuyet = new javax.swing.JLabel();
        timeBegin = new javax.swing.JLabel();
        timeEnd = new javax.swing.JLabel();
        diaChi = new javax.swing.JLabel();
        slThamGia = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));

        nameHN.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nameHN.setForeground(new java.awt.Color(51, 51, 51));
        nameHN.setText("jLabel4");

        xetDuyet.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        xetDuyet.setForeground(new java.awt.Color(204, 102, 0));
        xetDuyet.setText("jLabel5");

        timeBegin.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        timeBegin.setForeground(new java.awt.Color(51, 51, 51));
        timeBegin.setText("jLabel6");

        timeEnd.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        timeEnd.setForeground(new java.awt.Color(51, 51, 51));
        timeEnd.setText("jLabel7");

        diaChi.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        diaChi.setForeground(new java.awt.Color(51, 51, 51));
        diaChi.setText("jLabel8");

        slThamGia.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        slThamGia.setForeground(new java.awt.Color(0, 102, 204));
        slThamGia.setText("jLabel9");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Người tham gia");

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Đã diễn ra");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nameHN, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xetDuyet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(timeBegin, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(timeEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(slThamGia, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(diaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameHN, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(timeBegin)
                            .addComponent(timeEnd))
                        .addGap(18, 18, 18)
                        .addComponent(diaChi)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xetDuyet, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(slThamGia)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel diaChi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel nameHN;
    private javax.swing.JLabel slThamGia;
    private javax.swing.JLabel timeBegin;
    private javax.swing.JLabel timeEnd;
    private javax.swing.JLabel xetDuyet;
    // End of variables declaration//GEN-END:variables

    @Override
    public Component getListCellRendererComponent(JList<? extends Hoinghi> list, Hoinghi value, int index, boolean isSelected, boolean cellHasFocus) {

        if (isSelected) {
            this.setBackground(list.getSelectionBackground());
        } else { // when don't select
            this.setBackground(list.getBackground());
        }
        if (value.isBatDau()){
            jLabel2.setVisible(true);
        }
        else {
            jLabel2.setVisible(false);
        }
        NguoithamgiahoinghiId ntghnId = new NguoithamgiahoinghiId(Home.getCurrentUser().getId(), value.getId());
        Nguoithamgiahoinghi ntghn = NguoithamgiahoinghiDAO.get(ntghnId);
        nameHN.setText(value.getTen());
        if (ntghn!=null){
            xetDuyet.setText(ntghn.getIsallow()==0?"Đang xét duyệt":"Đã được xét duyệt");
        }
        else {
            xetDuyet.setText("Huỷ kiểm duyệt");
        }
        DateFormat dateFormat = new SimpleDateFormat("hh:mm dd/MM/yyyy");
        String strDay="DD/MM/YYYY";
        if (value.getThoigianbd()!= null) {
            strDay = dateFormat.format(value.getThoigianbd());
        }
        timeBegin.setText(strDay);
        if (value.getThoigiankt()!= null) {
            strDay = dateFormat.format(value.getThoigiankt());
        }
        timeEnd.setText(strDay);
        slThamGia.setText(value.getSoluongnguoithamgia()==null?"0/0":String.valueOf(value.getSoLuongDaThamGia())+'/'+String.valueOf(value.getSoluongnguoithamgia()));
        diaChi.setText(value.getDiadiem().getDiachi());
        JPanel panel = new JPanel();
        panel.setBackground(new Color(248,248,248));
        panel.add(this);
        panel.setBorder(new EmptyBorder(10,10, 10, 10));
        return panel;
    }
}
