/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package btl2.GUI;

import btl2.DAO.HoiNghiDAO;
import btl2.entiny.Hoinghi;
import java.awt.Color;
import java.awt.Component;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.ListCellRenderer;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author DELL
 */
public class HomeCardView extends javax.swing.JPanel implements ListCellRenderer<Hoinghi>{

    /**
     * Creates new form HomeCardView
     */
    public HomeCardView() {
        initComponents();
         this.setOpaque(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        img = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        timeBegin = new javax.swing.JLabel();
        timeEnd = new javax.swing.JLabel();
        people = new javax.swing.JLabel();
        detail = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 51)));

        name.setText("jLabel2");

        timeBegin.setText("jLabel3");

        timeEnd.setText("jLabel4");

        people.setText("jLabel5");

        detail.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(timeBegin)
                        .addGap(18, 18, 18)
                        .addComponent(timeEnd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(people)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(detail, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(img, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeBegin)
                    .addComponent(timeEnd)
                    .addComponent(people))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel detail;
    private javax.swing.JLabel img;
    private javax.swing.JLabel name;
    private javax.swing.JLabel people;
    private javax.swing.JLabel timeBegin;
    private javax.swing.JLabel timeEnd;
    // End of variables declaration//GEN-END:variables

    @Override
    public Component getListCellRendererComponent(JList<? extends Hoinghi> list, Hoinghi value, int index, boolean isSelected, boolean cellHasFocus) {
         name.setOpaque(true);
        detail.setOpaque(true);
        people.setOpaque(true);
        timeBegin.setOpaque(true);
        timeEnd.setOpaque(true);
        img.setOpaque(true);
        if (isSelected) {
            name.setBackground(list.getSelectionBackground());
            detail.setBackground(list.getSelectionBackground());
            people.setBackground(list.getSelectionBackground());
            timeBegin.setBackground(list.getSelectionBackground());
            timeEnd.setBackground(list.getSelectionBackground());
            img.setBackground(list.getSelectionBackground());
            this.setBackground(list.getSelectionBackground());
        } else { // when don't select
            name.setBackground(list.getBackground());
            detail.setBackground(list.getBackground());
            people.setBackground(list.getBackground());
             timeBegin.setBackground(list.getBackground());
            timeEnd.setBackground(list.getBackground());
            img.setBackground(list.getBackground());
            this.setBackground(list.getBackground());
        }

        // lbIcon.setIcon(new ImageIcon(getClass().getResource(
        //        "/nguyenvanquan7826/JList/" + value.getIconName() + ".jpg")));
        name.setText(value.getTen());
        detail.setText(value.getMota());
        people.setForeground(Color.blue);
        DateFormat dateFormat = new SimpleDateFormat("hh:mm dd/MM/yyyy");
        String strDay="DD/MM/YYYY";
        if (value.getThoigianbd()!= null) {
            strDay = dateFormat.format(value.getThoigianbd());
        }
        timeBegin.setText(strDay);
        if (value.getThoigiankt()!= null) {
            strDay = dateFormat.format(value.getThoigiankt());
        }
        if (HoiNghiDAO.getImg(value)!=""){
            img.setIcon(AddHoiNghi.ResizeImage(HoiNghiDAO.getImg(value), img));
        }
        timeEnd.setText(strDay);
        people.setText(value.getSoluongnguoithamgia()==null?"0/0":String.valueOf(value.getSoLuongDaThamGia())+'/'+String.valueOf(value.getSoluongnguoithamgia()));
        JPanel panel = new JPanel();
        panel.setBackground(Color.WHITE);
        panel.add(this);
        panel.setBorder(new EmptyBorder(5,5, 5, 5));
        return panel;
    }
}
