/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package btl2.GUI;

import btl2.entiny.Hoinghi;
import btl2.entiny.Nguoithamgiahoinghi;
import java.awt.Color;
import java.awt.Component;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.ListCellRenderer;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author DELL
 */
public class ItemUserJoin extends javax.swing.JPanel implements ListCellRenderer<Nguoithamgiahoinghi>{

    /**
     * Creates new form NewJPanel
     */
    Hoinghi hoinghi = null;
    public ItemUserJoin() {
        initComponents();
        this.setOpaque(true);
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 51)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public Component getListCellRendererComponent(JList<? extends Nguoithamgiahoinghi> list, Nguoithamgiahoinghi value, int index, boolean isSelected, boolean cellHasFocus) {
        jLabel1.setOpaque(true);
        if (isSelected) {
            jLabel1.setBackground(list.getSelectionBackground());
            this.setBackground(list.getSelectionBackground());
        } else { // when don't select
            jLabel1.setBackground(list.getBackground());
            this.setBackground(list.getBackground());
        }

        // lbIcon.setIcon(new ImageIcon(getClass().getResource(
        //        "/nguyenvanquan7826/JList/" + value.getIconName() + ".jpg")));
        jLabel1.setText("Người dùng: "+value.getUser().getUsername()+", id: "
                        +value.getUser().getId()+" muốn tham gia hội nghị: " 
                        + value.getHoinghi().getTen()+", có id: "+value.getHoinghi().getId());
        JPanel panel = new JPanel();
        panel.setBackground(Color.WHITE);
        panel.add(this);
        panel.setBorder(new EmptyBorder(10,10, 10, 10));
        return panel;
    }
}
